/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseInput: typeof import('./components/BaseInput.vue')['default']
    EssentialLink: typeof import('./components/EssentialLink.vue')['default']
    FormBaseInput: typeof import('./components/form/BaseInput.vue')['default']
    FormPostForm: typeof import('./components/form/PostForm.vue')['default']
    GlobalErrorDisplay: typeof import('./components/GlobalErrorDisplay.vue')['default']
    PostForm: typeof import('./components/PostForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UiEssentialLink: typeof import('./components/ui/EssentialLink.vue')['default']
    UiGlobalErrorDisplay: typeof import('./components/ui/GlobalErrorDisplay.vue')['default']
  }
}
